INSERT INTO product VALUES (1, 'CART MASTER', 0, 0);
INSERT INTO product VALUES (2, 'EMPRESTIMO CONSIG', 0, 1);
INSERT INTO product VALUES (3, 'CAP32', 0, 2);
INSERT INTO product VALUES (4, 'INVESTIMENTOS1', 0, 3);

