INSERT INTO product VALUES (1, 'CARTAO', 0, 0);
INSERT INTO product VALUES (2, 'EMPRESTIMO', 0, 1);
INSERT INTO product VALUES (3, 'CAPTALIZACAO', 0, 2);
INSERT INTO product VALUES (4, 'INVESTIMENTOS', 0, 3);

